import React from "react";
import Stonks from '../../../assets/images/stonks.webp'

const FEATURES = [
  {
    title: 'Real-Time Prices',
    description: 'Stock prices update every 7–8 seconds via WebSockets, giving you the feel of a live market without the real-world risk.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
      </svg>
    ),
    color: 'bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300',
  },
  {
    title: 'AI Buy Signal',
    description: 'Each stock page features an AI-powered signal — Perfect Time to Buy, Good, Risky, or Avoid — generated by Groq LLM using recent price history.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m1.636-6.364l.707.707M12 21v-1M7.05 17.95l.707-.707M16.95 17.95l-.707-.707M12 8a4 4 0 100 8 4 4 0 000-8z" />
      </svg>
    ),
    color: 'bg-purple-100 dark:bg-purple-900 text-purple-600 dark:text-purple-300',
  },
  {
    title: 'Virtual Currency',
    description: 'Every account starts with $100,000 in virtual coins. Buy and sell shares, monitor your portfolio, and track every transaction.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
    ),
    color: 'bg-yellow-100 dark:bg-yellow-900 text-yellow-600 dark:text-yellow-300',
  },
  {
    title: 'Add Funds via Razorpay',
    description: 'Run low on coins? Top up your balance instantly using Razorpay — a fully integrated payment flow with secure order creation and signature verification.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z" />
      </svg>
    ),
    color: 'bg-green-100 dark:bg-green-900 text-green-600 dark:text-green-300',
  },
];

const About = () => {
  return (
    <section className="bg-white dark:bg-gray-800">
      <div className="container px-16 sm:px-32 py-16 sm:py-24 mx-auto">
        <div className="items-center lg:flex">
          <div className="lg:w-1/2">
            <h2 className="text-3xl font-bold text-gray-800 dark:text-gray-100">What is Realtime Stock Simulator?</h2>
            <p className="mt-4 text-gray-500 dark:text-gray-400 lg:max-w-full">
              Realtime Stock Simulator is a full-stack trading platform with live price feeds, AI-powered buy signals, portfolio tracking, and integrated payments built to demonstrate real-world software engineering skills. Prices are randomly generated and are not reflective of real markets.
            </p>
          </div>

          <div className="mt-8 lg:mt-0 lg:w-1/2">
            <div className="flex items-center justify-center lg:justify-end">
              <div className="max-w-lg">
                <img className="opacity-90 object-cover object-center w-full h-72 rounded-md shadow" src={Stonks} alt="Stonks webp" />
              </div>
            </div>
          </div>
        </div>

        <div className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">
          {FEATURES.map((f) => (
            <div key={f.title} className="p-5 rounded-xl border border-gray-100 dark:border-gray-700 bg-gray-50 dark:bg-gray-900 flex flex-col gap-3">
              <div className={`w-10 h-10 flex items-center justify-center rounded-lg ${f.color}`}>
                {f.icon}
              </div>
              <h3 className="text-sm font-semibold text-gray-800 dark:text-gray-100">{f.title}</h3>
              <p className="text-xs text-gray-500 dark:text-gray-400 leading-relaxed">{f.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

export default About;

